"""add pdf storage fields

Revision ID: 8d6636426792
Revises: 32a12f25dc9a
Create Date: 2025-11-12 19:50:59.728438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6636426792'
down_revision: Union[str, Sequence[str], None] = '32a12f25dc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('notebook_pdf_s3_key', sa.String(length=500), nullable=True))
    op.add_column('pages', sa.Column('pdf_s3_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'pdf_s3_key')
    op.drop_column('notebooks', 'notebook_pdf_s3_key')
    # ### end Alembic commands ###
