"""add notebook metadata fields for folder hierarchy

Revision ID: d9e72c9e7ed9
Revises: 8d6636426792
Create Date: 2025-11-12 22:34:44.754721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e72c9e7ed9'
down_revision: Union[str, Sequence[str], None] = '8d6636426792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebooks', sa.Column('publisher', sa.String(length=255), nullable=True))
    op.add_column('notebooks', sa.Column('publication_date', sa.String(length=50), nullable=True))
    op.add_column('notebooks', sa.Column('pinned', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('notebooks', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('notebooks', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('notebooks', sa.Column('last_opened', sa.DateTime(), nullable=True))
    op.add_column('notebooks', sa.Column('last_opened_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebooks', 'last_opened_page')
    op.drop_column('notebooks', 'last_opened')
    op.drop_column('notebooks', 'version')
    op.drop_column('notebooks', 'deleted')
    op.drop_column('notebooks', 'pinned')
    op.drop_column('notebooks', 'publication_date')
    op.drop_column('notebooks', 'publisher')
    # ### end Alembic commands ###
