"""add notebook metadata fields for folder hierarchy

Revision ID: d9e72c9e7ed9
Revises: 8d6636426792
Create Date: 2025-11-12 22:34:44.754721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e72c9e7ed9'
down_revision: Union[str, Sequence[str], None] = '8d6636426792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Make migration idempotent - check if columns exist before adding
    from sqlalchemy import inspect
    from sqlalchemy.engine.reflection import Inspector

    conn = op.get_bind()
    inspector: Inspector = inspect(conn)
    existing_columns = {col['name'] for col in inspector.get_columns('notebooks')}

    # Add columns only if they don't exist
    if 'publisher' not in existing_columns:
        op.add_column('notebooks', sa.Column('publisher', sa.String(length=255), nullable=True))

    if 'publication_date' not in existing_columns:
        op.add_column('notebooks', sa.Column('publication_date', sa.String(length=50), nullable=True))

    if 'pinned' not in existing_columns:
        op.add_column('notebooks', sa.Column('pinned', sa.Boolean(), nullable=False, server_default='0'))

    if 'deleted' not in existing_columns:
        op.add_column('notebooks', sa.Column('deleted', sa.Boolean(), nullable=False, server_default='0'))

    if 'version' not in existing_columns:
        op.add_column('notebooks', sa.Column('version', sa.Integer(), nullable=True))

    if 'last_opened' not in existing_columns:
        op.add_column('notebooks', sa.Column('last_opened', sa.DateTime(), nullable=True))

    if 'last_opened_page' not in existing_columns:
        op.add_column('notebooks', sa.Column('last_opened_page', sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notebooks', 'last_opened_page')
    op.drop_column('notebooks', 'last_opened')
    op.drop_column('notebooks', 'version')
    op.drop_column('notebooks', 'deleted')
    op.drop_column('notebooks', 'pinned')
    op.drop_column('notebooks', 'publication_date')
    op.drop_column('notebooks', 'publisher')
    # ### end Alembic commands ###
